# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        image:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Linux cgo dependancies
      if: runner.os == 'Linux'
      run: |
        # sudo apt-get update

        # webview https://github.com/webview/webview_go/blob/master/.github/workflows/ci.yaml
        # sudo apt-get install -y libwebkit2gtk-4.0-dev

        # ebitengine: https://ebitengine.org/en/documents/install.html?os=linux#Debian_/_Ubuntu
        # sudo apt-get install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

        # raylib: https://github.com/gen2brain/raylib-go/blob/master/.github/workflows/build.yml
        # sudo apt-get install -y libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev

        # gtk: https://github.com/gotk3/gotk3/blob/master/.github/workflows/linux.yml
        # sudo apt-get install -y libgtk-3-dev libcairo2-dev libglib2.0-dev

    - name: Install MacOS cgo dependancies
      if: runner.os == 'macOS'
      run: |
        # b_gtk: https://github.com/gotk3/gotk3/blob/master/.github/workflows/macos.yml
        # brew install gobject-introspection gtk+3  

    - name: Build
      # Enable all features for CI builds. 
      run: |
        go build -v -o bin/rye
        ls -l bin/rye
        file bin/rye
        go version -m bin/rye

    - name: Run Rye Tests
      run: cd tests ; ../bin/rye main.rye test
      timeout-minutes: 1

    - name: Build WASM
      if: runner.os == 'Linux'
      run: |
        GOOS=js GOARCH=wasm go build -v -tags "b_tiny,b_wasm" -o wasm/rye.wasm main_wasm.go

#    - name: Test
#      run: go test -v -tags "b_tiny,b_sqlite,b_http,b_sql,b_postgres,b_openai,b_bson,b_crypto,b_smtpd,b_mail,b_postmark,b_bcrypt,b_telegram" ./...
